version: '3.8'

services:
  app-dev:
    container_name: rick-and-morty-development
    build: 
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    stdin_open: true
    tty: true